ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("profiles/", include("profiles.urls")),
    path("", include("shopping.urls")),
]

profiles/urls.py
from django.urls import path

from profiles.views import LoginView, LogoutView

app_name = "profiles"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

shopping/urls.py
from django.urls import path

from shopping.views import PurchaseView, CartConfirmView, CartItemRemoveView, OrderListView

app_name = "shopping"
urlpatterns = [
    path("", PurchaseView.as_view(), name="purchase"),
    path("cart/confirm/", CartConfirmView.as_view(), name="cart-confirm"),
    path("cart/items/<int:item_id>/remove", CartItemRemoveView.as_view(), name="cart-item-remove"),
    path("orders/", OrderListView.as_view(), name="order-list")
]

shopping/models/cart.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models

from profiles.models import UserProfile
from shopping.models import Item


class CartManager(models.Manager):
    """A custom manager for the Cart model.

    This manager provides a method for getting or creating a cart for a given user.

    """
    def get_or_create_by_user(self, user: UserProfile) -> "Cart":
        """Gets or creates a cart for a given user.

        Args:
            user: A UserProfile object representing the user to get or create a cart for.

        Returns:
            A Cart object representing the user's cart.

        """

        try:
            return user.cart
        except ObjectDoesNotExist:
            return self.create(user_profile=user)


class Cart(models.Model):
    """A model representing a user's shopping cart.

    Attributes:
        user_profile: A ForeignKey field linking to the UserProfile model representing the user who owns the cart.
        items: A ManyToManyField representing the items in the cart and their quantities.

    Properties:
        total_cost: An integer representing the total cost of all items in the cart.

    """
    user_profile: models.ForeignKey = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    items: models.ManyToManyField = models.ManyToManyField(Item, related_name="carts")

    objects = CartManager()

    @property
    def total_cost(self) -> int:
        """Calculates the total cost of all items in the cart.

        Returns:
            An integer representing the total cost of all items in the cart.

        """
        return self.items.aggregate(models.Sum("price"))["price__sum"] or 0

    def __str__(self) -> str:
        """Returns a string representation of the cart.

        Returns:
            A string representing the cart and its owner.

        """
        return f"{self.user_profile}'s cart"

shopping/models/item.py
from django.db import models


class Item(models.Model):
    """Represents an item that can be purchased in the online store.

    Attributes:
        name: The name of the item.
        price: The price of the item in USD.

    """

    name: models.CharField = models.CharField(max_length=256, blank=False, null=False)
    price: models.IntegerField = models.IntegerField(blank=False, null=False)

    def __str__(self) -> str:
        """Returns a string representation of the item, including its name and price.

        Returns:
            str: A string representation of the item.
        """
        return f"{self.name} ({self.price} USD)"

shopping/models/order.py
from django.db import models

from profiles.models import UserProfile
from shopping.models import Item


class Order(models.Model):
    """Represents an order made by a user.

    Attributes:
        user_profile: The user who made the order.
        items: The items that were ordered.
        created_at: The timestamp when the order was created.
    """
    user_profile: models.ForeignKey = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    items: models.ManyToManyField = models.ManyToManyField(Item, related_name="orders")
    created_at: models.DateTimeField = models.DateTimeField(auto_now_add=True)

    @property
    def total_cost(self) -> int:
        """Calculates the total cost of the order.

        Returns:
            int: The total cost in USD.
        """
        return self.items.aggregate(models.Sum("price"))["price__sum"] or 0

    def __str__(self) -> str:
        """Returns a string representation of the order.

        Returns:
            str: A string representation of the order.
        """
        return f"{self.user_profile}'s order"

shopping/forms/purchase.py
from django import forms

from shopping.models import Item


class PurchaseForm(forms.Form):
    """A form for selecting items to purchase.

    Attributes:
        items: A ModelMultipleChoiceField representing the items available for purchase.

    """
    items = forms.ModelMultipleChoiceField(queryset=Item.objects.all(), widget=forms.CheckboxSelectMultiple())

shopping/views.py
from typing import Hashable, Any, Optional, Union

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import QuerySet
from django.http import HttpResponse, HttpRequest, HttpResponsePermanentRedirect
from django.shortcuts import render, redirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, View, ListView

from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

import notifications.constants
from shopping.forms.purchase import PurchaseForm
from shopping.models import Cart
from shopping.models.order import Order


@method_decorator(login_required, name='dispatch')
class PurchaseView(TemplateView):
    """Renders a purchase form and handles form submission for adding items to the user's cart.

    Only accessible to authenticated users.

    Attributes:
        template_name: The name of the HTML template used to render the purchase form.

    Methods:
        get_context_data(**kwargs): Overrides the parent method to add a `PurchaseForm` instance to the context.

        post(request: HttpRequest) -> Union[HttpResponse, HttpResponsePermanentRedirect]: Handles form submission,
        adds the selected items to the user's cart, and redirects to the cart confirmation page on success.

    """
    template_name = "shopping/purchase.html"

    def get_context_data(self, **kwargs) -> dict[Hashable, Any]:
        """Overrides the parent method to add a `PurchaseForm` instance to the context.

        Args:
            **kwargs: Arbitrary keyword arguments.

        Returns:
            dict[Hashable, Any]: The updated context.
        """
        context = super(PurchaseView, self).get_context_data(**kwargs)
        return context | {"purchase_form": PurchaseForm()}

    def post(self, request: HttpRequest) -> Union[HttpResponse, HttpResponsePermanentRedirect]:
        """Handles form submission, adds the selected items to the user's cart, and redirects to the cart
           confirmation page on success.

        Args:
            request: The HTTP request object.

        Returns:
            Union[HttpResponse, HttpResponsePermanentRedirect]: A redirect to the cart confirmation page on success
                                                                or a rendered purchase form on error.
        """
        purchase_form = PurchaseForm(request.POST)

        if not purchase_form.is_valid():
            return render(
                request=request,
                context={
                    "purchase_form": purchase_form
                },
                template_name=self.template_name
            )

        cart = Cart.objects.get_or_create_by_user(request.user)
        to_be_added = [
            cart.items.through(cart=cart, item=item)
            for item in purchase_form.cleaned_data["items"]
            if item not in cart.items.all()
        ]
        cart.items.through.objects.bulk_create(to_be_added)

        return redirect("shopping:cart-confirm")


@method_decorator(login_required, name='dispatch')
class CartConfirmView(TemplateView):
    """View class that handles the cart confirmation process for a user.

    Attributes:
        template_name: The name of the HTML template that the view should render.

    Methods:
        get(request, *args, **kwargs): Ensure to initialize a cart for the user.
        post(request): Process payment, create a new order, flush the cart, and send a notification to the user.

    """
    template_name = "shopping/cart_confirm.html"

    def get(self, request: HttpRequest, *args, **kwargs) -> TemplateResponse:
        """Ensure to initialize a cart for the user.

        Args:
            request: The HTTP request object.
            args: Positional arguments passed to the method.
            kwargs: Keyword arguments passed to the method.

        Returns:
            A `TemplateResponse` object that renders the HTML template with the initialized cart.
        """
        Cart.objects.get_or_create_by_user(request.user)
        return super(CartConfirmView, self).get(request, *args, **kwargs)

    def post(self, request: HttpRequest) -> HttpResponsePermanentRedirect:
        """Process payment, create a new order, flush the cart, and send a notification to the user.

        Args:
            request: The HTTP request object.

        Returns:
            A `HttpResponsePermanentRedirect` object that redirects the user to the purchase page.
        """
        # Process payment should be added here.

        # Create a new order.
        order = Order.objects.create(user_profile=request.user)
        order.items.set(request.user.cart.items.all())

        request.user.cart.items.set([])  # Flush the cart contents.

        # Send a notification.
        async_to_sync(get_channel_layer().group_send)(
            notifications.constants.NOTIFICATIONS_GROUP_NAME_PREFIX + request.user.username,
            {
                "type": "notify",  # Custom Function written in the consumers.py
                "message": "A new order was placed successfully!",
            },
        )

        return redirect("shopping:purchase")


@method_decorator(login_required, name='dispatch')
class CartItemRemoveView(UserPassesTestMixin, View):
    """A view for removing an item from the user's shopping cart.

    Only superusers are allowed to remove items from a cart. Once an item is removed, the user will be redirected to the
    cart confirmation page.

    """
    def test_func(self) -> Optional[bool]:
        """Tests if the user is a superuser.

       Returns:
           bool: True if the user is a superuser, otherwise False.
       """
        return self.request.user.is_superuser

    def post(self, request: HttpRequest, item_id: int) -> HttpResponsePermanentRedirect:
        """Removes an item from the user's shopping cart and redirects the user to the cart confirmation page.

        Args:
            request: The request object.
            item_id: The ID of the item to remove.

        Returns:
            HttpResponsePermanentRedirect: A redirect to the cart confirmation page.
        """
        request.user.cart.items.remove(item_id)
        return redirect("shopping:cart-confirm")


@method_decorator(login_required, name='dispatch')
class OrderListView(ListView):
    """View to display a list of orders for the authenticated user.

    Attributes:
        model: The model used to retrieve the orders (Order).
        context_object_name: The name of the context variable containing the orders (orders).
        template_name: The name of the template used to render the view (shopping/order_list.html).

    Methods:
        get_queryset: Override the base method to filter orders by the user's profile.

    """
    model = Order
    context_object_name = "orders"
    template_name = "shopping/order_list.html"

    def get_queryset(self) -> QuerySet:
        """Overrides the base method to filter orders by the user's profile.

       Returns:
           A queryset of orders filtered by the user's profile.

       """
        return Order.objects.filter(user_profile=self.request.user)

shopping/templates/shopping/cart_confirm.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <title>E-Commerce</title>

    <!-- Latest compiled and minified CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

    <!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body>
  <div class="container pt-5">
      {% extends 'base.html' %}

    {% block title %} | Cart Confirmation{% endblock title %}

    {% block body %}
             <div class="container mt-5">

                <h2>Cart items:</h2>
                <p class="btn btn-warning float-right">Total cost: {{ user.cart.total_cost }}$</p>

                {% for item in user.cart.items.all %}
                    <p>
                        {{ item }}
                        {% if user.is_superuser %}
                        <form method="post" action="{% url "shopping:cart-item-remove" item.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger fa fa-trash"></button>
                        </form>
                        {% endif %}
                    </p>
                {% endfor %}

                <a class="btn btn-secondary" href="{% url "shopping:purchase" %}">Continue shopping..</a>


                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success float-right">Checkout</button>
                </form>
             </div>
    {% endblock body %}

  </div>

</body>

</html>

shopping/templates/shopping/order_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <title>E-Commerce</title>

    <!-- Latest compiled and minified CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

</head>
<body>
  <div class="container pt-5">
    {% extends "base.html" %}

    {% block title %} | My Orders{% endblock title %}

    {% block head %}
    <style>
        table, th, td {
          border: 1px solid black;
        }
    </style>
    {% endblock head %}

    {% block body %}
             <div class="container mt-5">

                {% if orders %}
                    <table class="table table-border table-sm">
                      <tr>
                        <th>ID</th>
                        <th>Created At (UTC)</th>
                        <th>Items</th>
                        <th>Total Cost in USD</th>
                      </tr>
                      {% for order in orders %}
                      <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.created_at }}</td>
                        <td>
                            <ul>
                              {% for item in order.items.all %}
                              <li>{{ item.name }}</li>
                              {% endfor %}
                            </ul>
                        </td>
                        <td>{{ order.total_cost }}</td>
                      </tr>
                      {% endfor %}
                    </table>
                {% else %}

                    <p>No orders!!  <a class="btn btn-secondary" href="{% url "shopping:purchase" %}">Go shopping..</a></p>
                {% endif %}
             </div>
    {% endblock body %}


  </div>

</body>

</html>

shopping/templates/shopping/purchase.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <title>E-Commerce</title>

    <!-- Latest compiled and minified CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

</head>
<body>
  <div class="container pt-5">
        {% extends 'base.html' %}
        {% block title %} | Purchase{% endblock title %}

        {% block body %}
       <div class="container mt-5">

        <h2>Item List:</h2>

        <p class="text-muted">Select items</p>
        <form method="POST" class="form-check">
            {% csrf_token %}

            {{ purchase_form.as_p }}

            {% if purchase_form.errors %}
            <div class="alert alert-danger">
                {{ purchase_form.errors }}
            </div>
            {% endif %}

            <button type="submit" class="btn btn-success">Add to cart</button>
        </form>
        {% endblock body %}

    </div>
  </div>

</body>

</html>