ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("profiles/", include("profiles.urls")),
    path("", include("shopping.urls")),
]

profiles/urls.py
from django.urls import path

from profiles.views import LoginView, LogoutView

app_name = "profiles"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

shopping/urls.py
from django.urls import path

from shopping.views import PurchaseView, CartConfirmView, CartItemRemoveView, OrderListView

app_name = "shopping"
urlpatterns = [
    path("", PurchaseView.as_view(), name="purchase"),
    path("cart/confirm/", CartConfirmView.as_view(), name="cart-confirm"),
    path("cart/items/<int:item_id>/remove", CartItemRemoveView.as_view(), name="cart-item-remove"),
    path("orders/", OrderListView.as_view(), name="order-list")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Meta -->
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">

      <title>E-Commerce{% block title %}{% endblock title %}</title>
      {% block head %}{% endblock head %}

      <!-- Latest compiled and minified CSS -->
      <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
  </head>

  <body>
       <div class="container pt-5">
            {% if user.is_authenticated %}
            <div class="container float-right"><p class="text-monospace float-right">Welcome! </p></div>
            <div class="container float-right"><p class="text-muted float-right"> {{ user }} </p></div>
            <div class="container float-right"><a href="{% url "profiles:logout" %}" class="btn btn-info float-right" >Logout</a></div>

                <a href="{% url "shopping:purchase" %}" class="btn btn-dark" >Go shopping</a>
                <a href="{% url "shopping:cart-confirm" %}" class="btn btn-dark" >View My Cart</a>
                <a href="{% url "shopping:order-list" %}"class="btn btn-dark" >View My Orders</a>
            {% endif %}
       </div>

    {% if user.is_authenticated %}
    <script>
        const notificationsSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/notifications/'
        );

        notificationsSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            alert(data.message);
        };

        notificationsSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
    </script>
    {% endif %}

    {% block body %} {% endblock body %}
  </body>

</html>